version: "3.9"

services:
  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8080:80"
      - "8443:8443"
    volumes:
      - ./webdata:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
      - ./nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro
      - ./htpasswd:/etc/nginx/.htpasswd:ro
      - ./gzip.conf:/etc/nginx/conf.d/gzip.conf:ro
    depends_on:
      - sftp

  sftp:
    image: atmoz/sftp
    container_name: sftp_server
    ports:
      - "2222:22"
    volumes:
      - ./webdata:/home/webuser/upload
    command: webuser:password:1001
